Feature/no01 css
beforeisland/ryosukemaejima pull request #2
Opened 2020-07-19 09:53 UTC by beforeisland

NRI模写、CSSでの装飾が完了しました。

2020-07-19 11:56 UTC, piasoratech requested changes
最大画面で表示した際にヘッダーの幅が短くなってしまっているので、幅が変動してサイズが合うようにしてください。
![image](https://user-images.githubusercontent.com/57445698/87874113-3a97e580-ca02-11ea-9c75-b74ff99b1420.png)

2020-07-19 13:28 UTC, beforeisland commented
> 最大画面で表示した際にヘッダーの幅が短くなってしまっているので、幅が変動してサイズが合うようにしてください。
> ![image](https://user-images.githubusercontent.com/57445698/87874113-3a97e580-ca02-11ea-9c75-b74ff99b1420.png)

修正完了

fix: ヘッダー固定メニュー修正	a455ad6	beforeisland <beforeisland@gmail.com>	2020/07/19 22:27

2020-07-20 08:42 UTC, piasoratech requested changes
全体的な指摘になります。
- 画像ファイルのサイズ指定はhtml側で行わずcss側で行うようにしてください。見た目に関することはcssにまとめるのが原則です。
- id名やclass名の命名規則がケバブケースとキャメルケースが混在しているので統一をしましょう。
- マジックナンバー(xxxx1,xxxxx2)での命名がされている部分があるので、修正してください。名前は見ただけでどんな全体的な指摘になります。
- 画像ファイルのサイズ指定はhtml側で行わずcss側で行うようにしてください。見た目に関することはcssにまとめるのが原則です。
- id名やclass名の命名規則がケバブケースとキャメルケースが混在しているので統一をしましょう。
- マジックナンバー(xxxx1,xxxxx2)での命名がされている部分があるので、修正してください。名前は見ただけでどんな内容なのかわかるようにしておく必要があります。

2020-07-20 12:33 UTC, beforeisland commented
> 全体的な指摘になります。
> 
> * 画像ファイルのサイズ指定はhtml側で行わずcss側で行うようにしてください。見た目に関することはcssにまとめるのが原則です。
> * id名やclass名の命名規則がケバブケースとキャメルケースが混在しているので統一をしましょう。
> * マジックナンバー(xxxx1,xxxxx2)での命名がされている部分があるので、修正してください。名前は見ただけでどんな全体的な指摘になります。
> * 画像ファイルのサイズ指定はhtml側で行わずcss側で行うようにしてください。見た目に関することはcssにまとめるのが原則です。
> * id名やclass名の命名規則がケバブケースとキャメルケースが混在しているので統一をしましょう。
> * マジックナンバー(xxxx1,xxxxx2)での命名がされている部分があるので、修正してください。名前は見ただけでどんな内容なのかわかるようにしておく必要があります。

下記コミットにて修正完了しました。

update: id,class命名規則の変更	66ee518	beforeisland <beforeisland@gmail.com>	2020/07/20 21:08

update: マジックナンバー付きclass名の修正及び装飾方法の変更	3a1a889	beforeisland <beforeisland@gmail.com>	2020/07/20 21:13

update: 画像のサイズ指定をhtml -> CSSへ変更	f2b8dce	beforeisland <beforeisland@gmail.com>	2020/07/20 21:30

2020-07-21 00:35 UTC, choimake reviewed
確認しました。最初に比べて格段によくなっているし、レイアウトもかなりできています。

いくつか修正して欲しい点がありますので、そちら対応お願いします。

- ヘッダーのUIの位置がオリジナルとくらべて中央に寄り過ぎているように見えます。（全画面）
提出物
<img width="801" alt="スクリーンショット 2020-07-21 9 15 20" src="https://user-images.githubusercontent.com/52233450/87998892-3370f480-cb34-11ea-817f-46ee54364456.png">
オリジナル
<img width="1426" alt="スクリーンショット 2020-07-21 9 15 41" src="https://user-images.githubusercontent.com/52233450/87998901-38ce3f00-cb34-11ea-8e5e-122e3392edc7.png">

- 全画面でみたときにやや余白が小さくみえます。
- 太字のフォントがオリジナルとくらべてやや薄いように見えます。

提出物
<img width="1418" alt="スクリーンショット 2020-07-21 9 16 49" src="https://user-images.githubusercontent.com/52233450/87999225-256fa380-cb35-11ea-8e05-2e438402e1ae.png">
オリジナル
<img width="1407" alt="スクリーンショット 2020-07-21 9 17 02" src="https://user-images.githubusercontent.com/52233450/87999220-1f79c280-cb35-11ea-867a-a580f81feab8.png">

- copyrightはpタグで囲む必要はないと思います(構造的に段落ではないのでは？）。スタイル当てるなら、smallタグにstyleあてれば良いかなと

2020-07-21 00:35 UTC, choimake commented on html-nri/common/css/style.css
> +}
ここにシンタックスエラーがあるので、チェッカーで確認して修正してください。

2020-07-22 13:16 UTC, beforeisland commented
> 確認しました。最初に比べて格段によくなっているし、レイアウトもかなりできています。
> 
> いくつか修正して欲しい点がありますので、そちら対応お願いします。
> 
> * ヘッダーのUIの位置がオリジナルとくらべて中央に寄り過ぎているように見えます。（全画面）
>   提出物
> 
> <img alt="スクリーンショット 2020-07-21 9 15 20" width="801" src="https://user-images.githubusercontent.com/52233450/87998892-3370f480-cb34-11ea-817f-46ee54364456.png">
> 
> オリジナル
> <img alt="スクリーンショット 2020-07-21 9 15 41" width="1426" src="https://user-images.githubusercontent.com/52233450/87998901-38ce3f00-cb34-11ea-8e5e-122e3392edc7.png">
> 
> * 全画面でみたときにやや余白が小さくみえます。
> * 太字のフォントがオリジナルとくらべてやや薄いように見えます。
> 
> 提出物
> <img alt="スクリーンショット 2020-07-21 9 16 49" width="1418" src="https://user-images.githubusercontent.com/52233450/87999225-256fa380-cb35-11ea-8e05-2e438402e1ae.png">
> オリジナル
> <img alt="スクリーンショット 2020-07-21 9 17 02" width="1407" src="https://user-images.githubusercontent.com/52233450/87999220-1f79c280-cb35-11ea-867a-a580f81feab8.png">
> 
> * copyrightはpタグで囲む必要はないと思います(構造的に段落ではないのでは？）。スタイル当てるなら、smallタグにstyleあてれば良いかなと

下記にて修正しました。
fix: 固定ヘッダーの装飾、中央寄り修正	a8d9c4f	beforeisland <beforeisland@gmail.com>	2020/07/22 20:59
fix: サブ記事リンク部分の装飾修正	785de8d	beforeisland <beforeisland@gmail.com>	2020/07/22 21:59
fix: コピーライト表記のタグ修正	4ca4cac	beforeisland <beforeisland@gmail.com>	2020/07/22 22:12

2020-07-22 13:17 UTC, beforeisland commented on html-nri/common/css/style.css
> +}
修正しました

fix: CSSシンタックスエラー修正	9cf1d5b	beforeisland <beforeisland@gmail.com>	2020/07/22 22:14

2020-07-23 02:56 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-07-23 02:56 UTC, choimake commented on html-nri/index.html
>      </div>
すいません。これ見落としてました。
page-top-icon、これはfooterタグ内に配置してください。

2020-07-24 07:19 UTC, beforeisland commented on html-nri/index.html
>      </div>
修正完了

fix: 右下アイコン周りのhtml構造修正

2020-07-24 07:27 UTC, choimake commented
LGTMです。次に進んでください。

2020-07-26 00:43 UTC, merged